version: '3.4'
services:
  node:
    build:
      context: .
      target: development
    command: npm run develop -- --host 0.0.0.0
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
