version: "3.4"
services:
  node:
    build:
      context: .
      target: development
    command: npm run develop
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
