version: '3.4'
services:
  node:
    build:
      context: .
      target: development
    command: npm run develop
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
